// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default async (req, res) => {
  res.status(200).json([
    {
      id: 134,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/134/',
      name: 'American Rocket Company',
      featured: false,
      type: 'Commercial',
      country_code: 'USA',
      abbrev: 'AMROC',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 125,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/125/',
      name: 'A.M. Makarov Yuzhny Machine-Building Plant',
      featured: false,
      type: 'Commercial',
      country_code: 'UKR',
      abbrev: 'PA Yuzhmash',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 84,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/84/',
      name: 'Amsat',
      featured: false,
      type: 'Commercial',
      country_code: 'USA,CAN,DEU,ITA,JPN,IND,GBR',
      abbrev: 'AMSAT',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 131,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/131/',
      name: 'Andrews Space',
      featured: false,
      type: 'Commercial',
      country_code: 'USA',
      abbrev: 'Andrews Space',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 190,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/190/',
      name: 'Antrix Corporation Limited',
      featured: false,
      type: 'Commercial',
      country_code: 'IND',
      abbrev: 'ACL',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 207,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/207/',
      name: 'Arab Satellite Communications Organization',
      featured: false,
      type: 'Commercial',
      country_code: 'SAU',
      abbrev: 'ASCO',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 115,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/115/',
      name: 'Arianespace',
      featured: true,
      type: 'Commercial',
      country_code: 'FRA',
      abbrev: 'ASA',
      description:
        'Arianespace SA is a multinational company founded in 1980 as the world\'s first commercial launch service provider. It undertakes the production, operation, and marketing of the Ariane programme. Their vehicles launch exclusively from French Guiana in South America.',
      administrator: 'CEO: Stéphane Israël',
      founding_year: '1980',
      launchers: 'Ariane 5 | Vega',
      spacecraft: '',
      parent: null,
      image_url:
        'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/arianespace_image_20190207032425.jpeg',
    },
    {
      id: 139,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/139/',
      name: 'Armadillo Aerospace',
      featured: false,
      type: 'Commercial',
      country_code: 'USA',
      abbrev: 'Armadillo',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 271,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/271/',
      name: 'Army Ballistic Missile Agency',
      featured: false,
      type: null,
      country_code: 'USA',
      abbrev: 'ABMA',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
    {
      id: 5,
      url: 'https://ll.thespacedevs.com/2.2.0/agencies/5/',
      name:
        'Asia Pacific Multilateral Cooperation in Space Technology and Applications',
      featured: false,
      type: 'Multinational',
      country_code: 'CHN,PAK,THA',
      abbrev: 'AP-MCSTA',
      description: null,
      administrator: null,
      founding_year: null,
      launchers: '',
      spacecraft: '',
      parent: null,
      image_url: null,
    },
  ]);
};
